blocus/config/routes.rb
Rails.application.routes.draw do
  get 'home/mypage' => "home#mypage"
  get 'home/list' => "home#list"

  resources :comments
  resources :events
  resources :infos
  root 'regions#index'

  get '/regions/:region_id/index' => "regions#index"
  get '/mypage' => "home#mypage"

  post '/damn' => "regions#myajax"
  post 'regions/nevy'

  post '/regions/replypost'

  resources :regions
  resources :bloks
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

blocus/app/models/event.rb
class Event < ApplicationRecord
  has_one :blok
end

blocus/app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @event = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render xml: @events }
    end
  end

  def new @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render xml: @event }
    end
  end

  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        flash[:notice] = 'Event was successfully created.'
        format.html { redirect_to(@event) }
        format.xml  { render xml: @event, status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.xml  { render xml: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render xml: @event }
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(events_url) }
      format.xml  { head :ok }
    end
  end

   private
  def event_params
    params.require(:event).permit(:type, :duration, :start, :end)
  end

end

blocus/app/helpers/events_helper.rb
module EventsHelper
end

blocus/app/views/events/_form.html.erb
<%= f.label :type, 'type' %>
<%= f.text_field :type%>
<%= f.submit "제출" %>

blocus/app/views/events/edit.html.erb
<%= form_for @event do |f| %>
  <%= render partial: 'form', locals: { :f => f } %>
<% end %>
<h1>여기는 수정하는 페이지 입니다</h1>

blocus/app/views/events/index.html.erb
<% @events.each do |r| %>
  </br>
  <%= r.lat %>,  <%= r.lng%>
  <%= link_to "자세하기", event_path(r)%>
<% end %>
</br>
<%= link_to "만들기", new_event_path %>

blocus/app/views/events/new.html.erb
<%= form_for @event do |f| %>
  <%= render partial: 'form', locals: { :f => f } %>
<% end %>
<h1>여기는 생성하는 페이지 입니다</h1>

blocus/app/views/events/show.html.erb
<%= @event.lat%>, <%= @event.lng %>
<%= link_to "수정하기", edit_event_path(@event) %>
<%= link_to "삭제하기", event_path(@event), method: 'delete' %>
<%= link_to "전체보기", :back %>


<a class="modal-trigger waves-effect waves-light btn" href="#modal1">Modal</a>

<!-- Modal Structure -->
<div id="modal1" class="modal modal-fixed-footer">
  <div class="modal-content">
    <h4>Modal Header</h4>
    <p>A bunch of text</p>
  </div>
  <div class="modal-footer">
    <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">Agree</a>
  </div>
</div>


<script>
  $(document).ready(function(){
  // the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
  $('.modal-trigger').leanModal();
  });    
  $('#modal1').openModal();
</script>