blocus/config/routes.rb
Rails.application.routes.draw do
  get 'home/mypage' => "home#mypage"
  get 'home/list' => "home#list"

  resources :comments
  resources :events
  resources :infos
  root 'regions#index'

  get '/regions/:region_id/index' => "regions#index"
  get '/mypage' => "home#mypage"

  post '/damn' => "regions#myajax"
  post 'regions/nevy'

  post '/regions/replypost'

  resources :regions
  resources :bloks
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

blocus/app/models/info.rb
class Info < ApplicationRecord
  has_one :blok
  has_many :comments
end

blocus/app/controllers/infos_controller.rb
class InfosController < ApplicationController
  def index
    @infos=Info.all
  end

  def new
    @info = Info.new
  end

  def create
    @info = Info.create(info_params)
    redirect_to infos_path
  end

  def show
    @info = Info.find(params[:id])
    redirect_to :back
  end

  def edit
    @info = Info.find(params[:id])
  end

  def update
    @info = Info.find(params[:id])
    @info.update(info_params)

    redirect_to info_path(@info)
  end

  def destroy
    @info = Info.find(params[:id])
    @info.destroy
    redirect_to infos_path
  end
  private
  def info_params
    params.require(:info).permit(:title, :content, :user_id, :blok_id)
  end

end

blocus/app/helpers/infos_helper.rb
module InfosHelper
end

blocus/app/views/infos/_form.html.erb
<%= f.label :content, 'content' %>
<%= f.text_field :content %>

<%= f.submit "제출" %>

blocus/app/views/infos/edit.html.erb
<%= form_for @info do |f| %>
  <%= render partial: 'form', locals: { :f => f } %>
<% end %>
<h1>여기는 수정하는 페이지 입니다</h1>

blocus/app/views/infos/index.html.erb
<% @infos.each do |r| %>
  </br>
  <%= link_to "#{r.content}", info_path(r)%>
<% end %>
</br>
<%= link_to "만들기", new_info_path %>

blocus/app/views/infos/new.html.erb
<%= form_for @info do |f| %>
  <%= render partial: 'form', locals: { :f => f } %>
<% end %>
<h1>여기는 생성하는 페이지 입니다</h1>

blocus/app/views/infos/show.html.erb
</br>
<%= @info.content %>
<%= link_to "수정하기", edit_info_path(@info) %>
<%= link_to "삭제하기", info_path(@info), method: 'delete' %>
<%= link_to "전체보기", :back %>