blocus/config/routes.rb
Rails.application.routes.draw do
  get 'home/mypage' => "home#mypage"
  get 'home/list' => "home#list"

  resources :comments
  resources :events
  resources :infos
  root 'regions#index'

  get '/regions/:region_id/index' => "regions#index"
  get '/mypage' => "home#mypage"

  post '/damn' => "regions#myajax"
  post 'regions/nevy'

  post '/regions/replypost'

  resources :regions
  resources :bloks
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

blocus/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, required: false
  belongs_to :info, required: false
end

blocus/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index 
    @comment = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render xml: @comments }
    end
  end
  
  def new 
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render xml: @comment }
    end
  end

  def create  
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        flash[:notice] = 'Comment was successfully created.'
        format.html { redirect_to(@comment) }
        format.xml  { render xml: @comment, status: :created, location: @comment }
      else
        format.html { render action: 'new' }
        format.xml  { render xml: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def show 
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render xml: @comment }
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update  
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update(comment_params)
        flash[:notice] = 'Comment was successfully updated.'
        format.html { redirect_to(@comment) }
        format.xml  { head :ok }
      else
        format.html { render action: 'edit' }
        format.xml  { render xml: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to(comments_url) }
      format.xml  { head :ok }
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :user_id, :info_id)
  end

end

blocus/app/helpers/comments_helper.rb
module CommentsHelper
end

blocus/app/views/comments/_form.html.erb
<%= f.label :comment, 'comment' %>
<%= f.text_field :comment%>
<%= f.submit "제출" %>

blocus/app/views/comments/edit.html.erb
<%= form_for @comment do |f| %>
  <%= render partial: 'form', locals: { :f => f } %>
<% end %>
<h1>여기는 수정하는 페이지 입니다</h1>

blocus/app/views/comments/index.html.erb
<% @comment.each do |r| %>
  </br>
  <%= r.content %>
  <%= link_to "자세하기", comment_path(r)%>
<% end %>
</br>
<%= link_to "만들기", new_comment_path %>

blocus/app/views/comments/new.html.erb
<%= form_for @comment do |f| %>
  <%= render partial: 'form', locals: { :f => f } %>
<% end %>
<h1>여기는 생성하는 페이지 입니다</h1>

blocus/app/views/comments/show.html.erb
<%= @comment.content%>
<%= link_to "수정하기", edit_comment_path(@comment) %>
<%= link_to "삭제하기", comment_path(@comment, method: 'delete' %>
<%= link_to "전체보기", :back %>