blocus/config/routes.rb
Rails.application.routes.draw do
  get 'home/mypage' => "home#mypage"
  get 'home/list' => "home#list"

  resources :comments
  resources :events
  resources :infos
  root 'regions#index'

  get '/regions/:region_id/index' => "regions#index"
  get '/mypage' => "home#mypage"

  post '/damn' => "regions#myajax"
  post 'regions/nevy'

  post '/regions/replypost'

  resources :regions
  resources :bloks
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

blocus/app/models/region.rb
class Region < ApplicationRecord
  has_many :bloks
end

blocus/app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    @regions=Region.all
  end

  def new
    @region = Region.new
  end

  def create
    @region = Region.create(region_params)
    redirect_to regions_path
  end

  def myajax
    @blok = params[:blok_num].to_i
    @key = params[:key].to_i
    @ans = Blok.search(@blok,@key)
    @month = Info.find(@ans).created_at.month
    @day = Info.find(@ans).created_at.day
    @email = User.find(Blok.find(@ans).user_id).email

    @info = Info.find(@ans)
    data = {:message => @ans, :content => @info.content, :email => @email, :month => @month, :day => @day}
    render :json => data, :status => :ok
  end
  def show
    @bloks = Blok.all
    @blok = Blok.new
    @lat = 0
    @lng = 0
    @region = Region.find(params[:id])
  end

  def edit
    @region = Region.find(params[:id])
  end

  def update
    @region = Region.find(params[:id])
    @region.update(region_params)

    redirect_to region_path(@region)
  end

  def destroy
    @region = Region.find(params[:id])
    @region.destroy
    redirect_to regions_path
  end

  def replypost
    @comment=Comment.new
    @comment.content=params[:reply]
    @comment.info_id=params[:info_id]
    @comment.save
    @info=Info.find(params[:info_id])
  end

  def nevy
    @b_id = Blok.search(params[:up_input], 38)
    puts @b_id

  end

  private
  def region_params
    params.require(:region).permit(:name)
  end

end

blocus/app/helpers/regions_helper.rb
module RegionsHelper
end

blocus/app/views/regions/_form.html.erb
<%= f.label :name, 'name' %>
<%= f.text_field :name %>
<%= f.submit "제출" %>

blocus/app/views/regions/_from.html.erb
<%= f.label :name, 'name' %>
<%= f.text_field :name %>
<%= f.submit "제출" %>

blocus/app/views/regions/_infowindows.html.erb
<%= form_for @blok do |f| %>
  <%= f.submit "블록 차지하기" %>
<% end %>

blocus/app/views/regions/_newpost.html.erb
<%= form_for Info.find(info_id), remote: true do |f| %>
  <%= f.text_field :content %>
<% end %>

blocus/app/views/regions/_next.html.erb
<% puts b_id %>

<input name="up_input2" id="up_input2" type="hidden" value=<%= b_id %>>

blocus/app/views/regions/_replylist.html.erb
<% info.comments.each do |r| %>
  <%= r.content %>
  </br>
<% end %>

blocus/app/views/regions/_sns.html.erb
<!-- 내용 -->
<a class="pull-left" href="#">
  <img class="media-object" src="http://placehold.it/55x55" alt="">
</a>
<p><strong> &nbsp <%=User.find(Blok.find(info_id).user_id).email %> </strong></p>
<p><font size='2'> &nbsp <%= Info.find(info_id).created_at.month %>월 <%= Info.find(info_id).created_at.day %>일    </font>  </p>
<hr>
<%= image_tag asset_path('iu.jpg'), height: '268', width: '368' %>
<hr>
<div id='content'><%= Info.find(info_id).content %> </div>

<% if Info.find(info_id).content == "" %>
  <p> 글이 아직 없습니다 <p>
  <%= render partial: 'newpost', locals: {info_id: info_id}%>
<% end %>

<hr>
<!-- 댓글 -->
<div id="post_list">
  <% Info.find(info_id).comments.each do |r| %>
    <p> <%= r.content %> </p>
    </br>
  <% end %>
</div>
<div class="row">
<%= form_tag regions_replypost_path(info_id: info_id), method: "POST", remote: true do %>
    <input type="text" class="form-control" name="reply" id="reply" placeholder="댓글을 입력하세요.">
<% end %>
</div>

blocus/app/views/regions/edit.html.erb
<%= form_for @region do |f| %>
  <%= render partial: 'from', locals: { :f => f } %>
<% end %>
<h1>여기는 수정하는 페이지 입니다</h1>

blocus/app/views/regions/index.html.erb
<div class="container">
<% @regions.each do |r| %>
  </br>
  <%= link_to "#{r.name}", region_path(r)%>
<% end %>
<%= link_to "만들기", new_region_path %>
</div>

blocus/app/views/regions/nevy.js.erb
<% puts @b_id %>
<% if Info.where(id: @b_id).take != nil %>
    <% if Info.find(@b_id).content != "" %>
        $('#sns').html("<%= escape_javascript(render partial: 'sns', locals: { info_id: @b_id  })%>");
  <% elsif Blok.find(@b_id).user_id == current_user.id %>
    $('#sns').html("<%= escape_javascript(render partial: 'newpost', locals: { info_id: @b_id  })%>");
  <% else %>
      $('#sns').html('<p> 글이 없는 블록입니다.</p>');
  <% end %>
<% end %>
$('#up_form2').remove()
$('#up_form').append("<%= escape_javascript(render partial: 'next', locals: { b_id: @b_id }) %>" );

blocus/app/views/regions/new.html.erb
<%= form_for @region do |f| %>
  <%= render partial: 'from', locals: { :f => f } %>
<% end %>
<h1>여기는 생성하는 페이지 입니다</h1>

blocus/app/views/regions/newnew.js.erb
$("#sns").html("<%=Time.now %>")

blocus/app/views/regions/replypost.js.erb
$("#post_list").html(
   "<%= escape_javascript(render partial: 'replylist', locals: { info: @info }) %>"
);


$("#reply").val("");

blocus/app/views/regions/show.html.erb
<div class="row">
  <div class="col-md-8">
    <input id="pac-input" class="controls" type="text" style="margin-top:12px" placeholder="Search Box">
    <div id="map" style="height:650px"></div>
  </div>
  <div class="col-md-4" id="sns" style="overflow:auto; height:700px; margin-top:20px"></div>
</div>


<%= form_tag regions_nevy_path, id: 'up_form', remote: true do %>
  <%= button_tag "up_submit", type: "submit hidden", id: "up_submit" %>
<% end %>


<script>
  var current
  var map
  var current_marker
  var current_pos
  var current_op
  function CenterControl(controlDiv, map) {

    // Set CSS for the control border.
    var controlUI = document.createElement('div');
    controlUI.style.backgroundColor = '#fff';
    controlUI.style.border = '2px solid #fff';
    controlUI.style.borderRadius = '3px';
    controlUI.style.boxShadow = '0 2px 6px rgba(0,0,0,.3)';
    controlUI.style.cursor = 'pointer';
    controlUI.style.marginTop = '12px';
    controlUI.style.position = 'absolute';
    controlUI.style.right = '-390px';
    controlUI.title = 'GPS'
    controlDiv.appendChild(controlUI);

    // Set CSS for the control interior.
    var controlText = document.createElement('div');
    controlText.style.color = 'rgb(25,25,25)';
    controlText.style.fontFamily = 'Roboto,Arial,sans-serif';
    controlText.style.fontSize = '16px';
    controlText.style.lineHeight = '38px';
    controlText.style.paddingLeft = '5px';
    controlText.style.paddingRight = '5px';
    controlText.innerHTML = '현재위치';
    controlUI.appendChild(controlText);

    // 누르면 현재위치 표시 및 마크 생성
    controlUI.addEventListener('click', function() {
      if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(function(position) {
          var pos = {
            lat: position.coords.latitude,
            lng: position.coords.longitude
          };

          current_pos = pos;

          current_marker = new google.maps.Marker({
            position: pos,
            map: map,
          });
          current_op = 1;

          map.setCenter(pos);
          }, function() {
          handleLocationError(true, infoWindow, map.getCenter());

        });
        } else {
        // Browser doesn't support Geolocation
        handleLocationError(false, infoWindow, map.getCenter());
      }
    });

  }

  // 키 누르면 마크 이동
  document.onkeydown = checkKey;

  function checkKey(e) {
    // 현재 위치 표시 될때만 이동됨
    if (current_op == 1){

      e = e || window.event;

      step = 0.005;

      if (e.keyCode == '38') {
        current_pos["lat"] = current_pos["lat"] + step;
        current_marker.setPosition(current_pos);
        map.setCenter(current_pos);
        // up arrow
      }
      else if (e.keyCode == '40') {
        current_pos["lat"] = current_pos["lat"] - step;
        current_marker.setPosition(current_pos);
        map.setCenter(current_pos);
        // down arrow
      }
      else if (e.keyCode == '37') {
        current_pos["lng"] = current_pos["lng"] - step;
        current_marker.setPosition(current_pos);
        map.setCenter(current_pos);
        // left arrow
      }
      else if (e.keyCode == '39') {
        current_pos["lng"] = current_pos["lng"] + step;
        current_marker.setPosition(current_pos);
        map.setCenter(current_pos);
        // right arrow
      }
    }
  }

  function initMap() {
    // Create a map object and specify the DOM element for display.
    map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: Number('<%= @region.lat %>'), lng: Number('<%= @region.lng %>')},
      scrollwheel: false,
      zoom: 15
    });
    var input = document.getElementById('pac-input');
      var searchBox = new google.maps.places.SearchBox(input);
      map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

      // Bias the SearchBox results towards current map's viewport.
      map.addListener('bounds_changed', function() {
        searchBox.setBounds(map.getBounds());
      });

      var markers = [];
      // [START region_getplaces]
      // Listen for the event fired when the user selects a prediction and retrieve
      // more details for that place.
      searchBox.addListener('places_changed', function() {
        var places = searchBox.getPlaces();

        if (places.length == 0) {
          return;
        }

        // Clear out the old markers.
        markers.forEach(function(marker) {
          marker.setMap(null);
        });
        markers = [];

        // For each place, get the icon, name and location.
        var bounds = new google.maps.LatLngBounds();
        places.forEach(function(place) {
          var icon = {
            url: place.icon,
            size: new google.maps.Size(71, 71),
            origin: new google.maps.Point(0, 0),
            anchor: new google.maps.Point(17, 34),
            scaledSize: new google.maps.Size(25, 25)
          };

          // Create a marker for each place.
          markers.push(new google.maps.Marker({
            map: map,
            icon: icon,
            title: place.name,
            position: place.geometry.location
          }));

          if (place.geometry.viewport) {
            // Only geocodes have viewport.
            bounds.union(place.geometry.viewport);
          } else {
            bounds.extend(place.geometry.location);
          }
        });
       // map.fitBounds(bounds);
         map.setCenter(bounds.getCenter())
         map.setZoom(17)
      });
///////////////////////
      var centerControlDiv = document.createElement('div');
      var centerControl = new CenterControl(centerControlDiv, map);

      centerControlDiv.index = 1;
      map.controls[google.maps.ControlPosition.TOP_CENTER].push(centerControlDiv);
    //// Zoom change ////
  /*  google.maps.event.addListener(map, 'zoom_changed', function() {
      <% Blok.all.each do |b| %>
        <% unless Info.where(blok_id: b.id).take==nil  %>
          var flag = 1
          rectangle['<%=b.id%>'].setMap();
          if(map.getZoom() <=13) {
            <% if Info.find(b.id).popularity <= 30 %>
              flag = 0
            <% end %>
          }
          if(map.getZoom() ==14) {
            <% if Info.find(b.id).popularity <= 20 %>
              flag = 0
            <% end %>
          }
          if(map.getZoom() ==15) {
            <% if Info.find(b.id).popularity <= 10 %>
              flag = 0
            <% end %>
          }
          if(map.getZoom() >=16) {
            <% if Info.find(b.id).popularity <= 5 %>
              flag = 0
            <% end %>
          }

          if(flag) {
            rectangle['<%=b.id%>'] = new google.maps.Rectangle({
              strokeColor: 'green',
              strokeOpacity: 0.8,
              strokeWeight: 1,
              fillColor: 'green',
              fillOpacity: 0.5,
              map: map,
              bounds: {
                north: Math.floor('<%=b.lat%>'/0.00027)*0.00027,
                south: Math.floor('<%=b.lat%>'/0.00027+1)*0.00027,
                east: Math.floor('<%=b.lng%>'/0.00034+1)*0.00034,
                west: Math.floor('<%=b.lng%>'/0.00034)*0.00034
            }});
            rectangle['<%=b.id%>'].addListener('click', function() {

              current_rectangle = new google.maps.Rectangle({
              strokeColor: 'blue',
              strokeOpacity: 0.8,
              strokeWeight: 1,
              fillColor: 'green',
              fillOpacity: 0.5,
              map: map,
              bounds: {
              north: Math.floor('<%=b.lat%>'/0.00027)*0.00027,
              south: Math.floor('<%=b.lat%>'/0.00027+1)*0.00027,
              east: Math.floor('<%=b.lng%>'/0.00034+1)*0.00034,
              west: Math.floor('<%=b.lng%>'/0.00034)*0.00034
              }});



              $('#sns').html("<%= escape_javascript(render partial: 'sns', locals: { info_id: b.id  })%>");
            })
          }
        <% end %>
      <% end %>

    });
    */
    ///////zoom 되기 전///////////////

    var current_rectangle = new google.maps.Rectangle({
        strokeColor: 'green',
        strokeOpacity: 0.8,
        strokeWeight: 1,
        fillColor: 'green',
        fillOpacity: 0.5,
        map: map,
        bounds: {
          north: 0,
          south: 0,
          east: 0,
          west: 0
      }});
   var rectangle = []
    <% Blok.all.each do |b| %>
      rectangle['<%=b.id%>'] = new google.maps.Rectangle({
        id: '<%=b.id%>',
        strokeOpacity: 0.8,
        strokeWeight: 1,
        <% if b.user_id.to_i == current_user.id %>
          strokeColor: 'pink',
          fillColor: 'pink',
        <% else %>
          strokeColor: 'green',
          fillColor: 'green',
        <% end %>
        fillOpacity: 0.5,
        map: map,
        bounds: {
          north: Math.floor('<%=b.lat%>'/0.00027)*0.00027,
          south: Math.floor('<%=b.lat%>'/0.00027+1)*0.00027,
          east: Math.floor('<%=b.lng%>'/0.00034+1)*0.00034,
          west: Math.floor('<%=b.lng%>'/0.00034)*0.00034
      }});


      rectangle['<%=b.id%>'].addListener('click', function() {

      current_op=2
        <% if b.user_id.to_i == current_user.id %>
          current_rectangle.setOptions({fillColor: 'pink', strokeColor: 'pink'});
        <% else %>
          current_rectangle.setOptions({fillColor: 'green', strokeColor: 'green'});
        <% end %>

        current_rectangle = rectangle['<%=b.id%>']
        current_rectangle.setOptions({fillColor: 'blue', strokeColor: 'blue'});

        <% if Info.where(id:b.id).take != nil %>
          <% if Info.find(b.id).content != "" %>
          $('#sns').html("<%= escape_javascript(render partial: 'sns', locals: { info_id: b.id  })%>");
          <% elsif b.user_id == current_user.id %>
             $('#sns').html("<%= escape_javascript(render partial: 'newpost', locals: { info_id: b.id  })%>");
          <% else %>
             $('#sns').html('<p> 글이 없는 블록입니다.</p>');
          <% end %>
        <% end %>
      })

    <% end %>
    $(document).keydown(function(e) {
    // 현재 위치 표시 될때만 이동됨
    if ( current_op == 2 && e.keyCode >=37 && e.keyCode<=40 ){
    e = e || window.event;

    e.preventDefault();
    $.ajax({
    dataRemote: "true",
    type: "POST",
    url: "/damn",
    data: {blok_num: Number(current_rectangle['id']), key: Number(e.keyCode)},
    success: function(data,status,xhr){

    next = data.message
    current_rectangle.setOptions({fillColor: 'green', strokeColor: 'green'});
    current_rectangle = rectangle[next]
    current_rectangle.setOptions({ fillColor: 'blue', strokeColor: 'blue'  })
    map.setCenter(current_rectangle.getBounds().getNorthEast());

    $('#sns').html('<a class="pull-left" href="#">  <img class="media-object" src="http://placehold.it/55x55" alt=""> </a> <p><strong> &nbsp' + data.email + '</strong></p> <p><font size="2"> &nbsp'+ data.month +'월 ' +  data.day +'일    </font>  </p>  <hr> <%= image_tag asset_path("iu.jpg"), height: "268", width: "368" %> <hr> <div id="content">'+data.content+ '</div>' );
    if(data.content == "") {
       $('#sns').append('<p> 글이 아직 없습니다 <p>');
       $('#sns').append('');

    }
    },
    error: function(xhr,status,error){
    console.log(xhr);
    alert(error);
    }
    })

    }
    })

    map.addListener('mousemove', function(e) {

      var infowindow = new google.maps.InfoWindow();
      var rectangle = new google.maps.Rectangle({
        strokeColor: 'black',
        strokeOpacity: 0.8,
        strokeWeight: 1,
        fillColor: 'black',
        fillOpacity: 0.5,
        map: map,
        bounds: {
          north: Math.floor(e.latLng.lat()/0.00027)*0.00027,
          south: Math.floor(e.latLng.lat()/0.00027+1)*0.00027,
          east: Math.floor(e.latLng.lng()/0.00034+1)*0.00034,
          west: Math.floor(e.latLng.lng()/0.00034)*0.00034
      }});
      this.addListener('mousemove', function() {
        rectangle.setMap();
        infowindow.close();
      });
      rectangle.addListener('click', function() {
        rectangle.setOptions({ fillColor: 'red'});
        var ne = rectangle.getBounds().getNorthEast();
        var nw = new google.maps.LatLng(ne.lat()+0.000135,ne.lng()-0.00017);
        infowindow.setContent('<%= escape_javascript(render partial: "infowindows", locals: {} ) %>');
        infowindow.setPosition(nw);
        infowindow.open(map);
        $('#new_blok').append('<input name="blok[lat]" type="hidden" value='+ ne.lat()+'>');
        $('#new_blok').append('<input name="blok[lng]" type="hidden" value='+ ne.lng()+'>');
      });

    });
}
</script>
<script src='https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_KEY'] %>&callback=initMap&libraries=geometry,places'
  async defer></script>